# Generated by Django 2.1.2 on 2022-11-09 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20221108_1549'),
        ('restaurant', '0002_auto_20221107_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='barrier_free_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.BarrierFreeInfo'),
        ),
    ]
