# Generated by Django 2.1.2 on 2022-10-31 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarrierFreeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.CharField(max_length=200)),
                ('slope', models.CharField(max_length=200)),
                ('is_accessible_toilet', models.BooleanField()),
                ('is_braille', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Location'),
        ),
    ]
