# Generated by Django 2.1.5 on 2022-11-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barrierfreeinfo',
            old_name='entrance',
            new_name='entrance_form',
        ),
        migrations.RenameField(
            model_name='barrierfreeinfo',
            old_name='slope',
            new_name='entrance_ramp',
        ),
        migrations.RemoveField(
            model_name='barrierfreeinfo',
            name='is_accessible_toilet',
        ),
        migrations.RemoveField(
            model_name='barrierfreeinfo',
            name='is_braille',
        ),
        migrations.RemoveField(
            model_name='barrierfreeinfo',
            name='location',
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='elevator_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='elevator_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='elevator_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='entrance_braille',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='entrance_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='entrance_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='parking_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='parking_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='parking_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='restroom_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='restroom_floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='barrierfreeinfo',
            name='restroom_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
