# Generated by Django 2.1.5 on 2022-11-08 06:49

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20221107_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierfreeinfo',
            name='elevator_img',
            field=models.ImageField(null=True, upload_to=common.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='barrierfreeinfo',
            name='entrance_img',
            field=models.ImageField(null=True, upload_to=common.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='barrierfreeinfo',
            name='parking_img',
            field=models.ImageField(null=True, upload_to=common.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='barrierfreeinfo',
            name='restroom_image',
            field=models.ImageField(null=True, upload_to=common.models.get_file_path),
        ),
    ]
