# Generated by Django 2.1.2 on 2022-11-30 03:10

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20221108_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBFinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_value', models.CharField(max_length=200)),
                ('info_img', models.ImageField(null=True, upload_to=common.models.get_file_path)),
                ('info_detail', models.TextField(null=True)),
            ],
        ),
    ]
