# Generated by Django 2.1.5 on 2022-11-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20221108_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='barrier_free_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.BarrierFreeInfo'),
        ),
    ]
