# Generated by Django 2.1.5 on 2022-11-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_location_barrier_free_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barrierfreeinfo',
            old_name='restroom_image',
            new_name='restroom_img',
        ),
    ]
