# Generated by Django 2.1.5 on 2022-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='createdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
