# Generated by Django 2.1.2 on 2022-12-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_imgupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgUpload',
        ),
    ]
