# Generated by Django 2.1.2 on 2022-12-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_delete_imgupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='writer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
