# Generated by Django 2.1.5 on 2022-11-07 10:16

from django.db import migrations, models
import django.db.models.deletion
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20221107_0057'),
        ('testapp', '0002_auto_20221107_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimage',
            name='fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Location'),
        ),
        migrations.AlterField(
            model_name='testimage',
            name='img',
            field=models.ImageField(null=True, upload_to=testapp.models.get_file_path),
        ),
    ]
