# Generated by Django 2.1.5 on 2022-11-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20221107_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Location'),
        ),
    ]
