# Generated by Django 2.1.5 on 2022-11-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20221107_0057'),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='name',
            new_name='building_name',
        ),
        migrations.AddField(
            model_name='campus',
            name='bottom_floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='building_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Location'),
        ),
        migrations.AddField(
            model_name='campus',
            name='top_floor',
            field=models.IntegerField(null=True),
        ),
    ]
